### ISSUE TITLE
 iOS webview inspect stop working 

### ISSUE THREAD

**Issue by marcanw** [distriqt/ANE-GooglePlayServices#29] opened 2023-09-29 09:29 UTC
After upgrading my iPhone, I can no longer inspect Stagewebview from Mac/Safari.
I saw that a new flag has been added on the webview for iOS 16.4+:
https://developer.apple.com/documentation/webkit/wkwebview/4111163-isinspectable

Do you plan to make something about it?

Thx.

**Comment by marchbold** [comment] 2023-10-01 06:03
Duplicate of https://github.com/distriqt/ANE-NativeWebView/issues/316

Yes we will get this added in the next release.

**Closed by marchbold** 2023-10-01 06:03 UTC
